### ISSUE TITLE
Disable Automatic Trigger on single change

### ISSUE THREAD

**Issue by KeremTurkyilmaz** [iamtimsmith/wp-trigger-netlify-build#13]
It would be useful to disable the trigger on each change and do it only at the end of all user changes. Via the "Trigger Build" button.

This allows you to not build the site on each change, and spend unnecessary minutes on Netlify free plan.

Add a switch button to enable or disable automatic build hook.

**Comment by SRFeesha** [comment]
@KeremTurkyilmaz 

So I'm no expert in PHP, but I managed to disable the auto-deploy on save and trigger a netlify deploy only when clicking on the button for manual deploy in the dashboard home of WP.

No fancy toggle to disable and enable auto deploy — it's honestly a half-ass custom solution suited only for my need. But hey, maybe it could suits also your needs!

[Here is my fork which enable deploy to be triggered only manually](https://github.com/SRFeesha/wp-trigger-netlify-build/tree/manual-deploy-only)

**Comment by KeremTurkyilmaz** [comment]
@SRFeesha Thank you, I'll take a look !
